Feature/add exercrise 1
quangha12thxd/JavaExercise pull request #1
Opened 2019-05-14 14:30 UTC by quangha12thxd

2019-05-14 15:03 UTC, voquanghoa requested changes

2019-05-14 15:03 UTC, voquanghoa commented on src/main/java/BT1/Fibonaci.java
> +        int tam;
Biến `tam` này nên move vào bên trong vòng while và tên đặt tên ok hơn chút là `temp`

2019-05-14 15:03 UTC, voquanghoa commented on src/main/java/BT1/Fibonaci.java
> +    return str.toString();
Lệnh `return` này bị sai tab. Tức là nằm hơi lệch về bên trái

2019-05-14 15:03 UTC, voquanghoa commented on src/main/java/BT1/Fibonaci.java
> +public class Fibonaci {
Cần phải có dòng trống vào giữa 3 phần này nha
```
package BT1;
<dòng trống>
các câu lệnh import
<dòng trống>
Khai báo class
<dòng trống>
khai báo method
```
```

2019-05-14 15:03 UTC, voquanghoa commented on src/main/java/BT1/Fibonaci.java
> +    public String Fibonaci(int n) {
Tên hàm phải viết thường `fibonaci`

2019-05-14 15:03 UTC, voquanghoa commented on src/main/java/BT1/PTB2.java
> +public class PTB2 {
Tương tự review ở trên, ở đây mình thiếu các dòng trống

2019-05-14 15:03 UTC, voquanghoa commented on src/main/java/BT1/PTB2.java
> +                x1 = (double) Math.round(((-b + Math.sqrt(delta)) / 2 / a)*100)/100;
Đừng làm tròn làm gì cả. Chỉ cần thế này là được

![Screen Shot 2019-05-14 at 9 48 34 PM](https://user-images.githubusercontent.com/10450325/57707653-2a63d800-7692-11e9-9542-8cdb8d0d6753.png)

2019-05-14 15:03 UTC, voquanghoa commented on src/main/java/BT1/PTB2.java
> +        double delta;
Biến delta nên được khai báo ở dòng 25

2019-05-14 15:03 UTC, voquanghoa commented on src/main/java/BT1/PTB2.java
> +    // Kiem tra gia tri a
Xóa hết comment trong code

2019-05-14 15:03 UTC, voquanghoa commented on src/main/java/BT1/PTB2.java
> +        double x1, x2;
Nên move dòng khai báo x1, x2 vào nơi nó được tính

2019-05-14 15:03 UTC, voquanghoa commented on src/main/java/BT1/TichTSNT.java
> +            return kq.toString();
```java
kq.append("So vua nhap khong phai so nguyen!!!");
return kq.toString();
```
Nên viết thành
```java
return "So vua nhap khong phai so nguyen!!!";
```

2019-05-14 15:03 UTC, voquanghoa commented on src/main/java/BT1/TichTSNT.java
> +        StringBuffer kq = new StringBuffer();
Biến `i` và `kq` nên move xuống dưới chổ dùng nó

2019-05-14 15:03 UTC, voquanghoa commented on src/main/java/BT1/TichTSNT.java
> +    return kq.toString();
Dòng `return` viết sai tab

2019-05-14 15:03 UTC, voquanghoa commented on src/main/java/BT1/TichTSNT2.java
> +        int i, somu;
Biến `i` và `somu ` phải khai báo ngay trong vòng lặp

2019-05-14 15:03 UTC, voquanghoa commented on src/main/java/BT1/TichTSNT2.java
> +            return kq.toString();
Như review trên

2019-05-14 15:03 UTC, voquanghoa commented on src/main/java/BT1/TichTSNT2.java
> +                if (somu == 1) {
```java
                if (somu == 1) {
                    kq.append(i);
                }
                else {
                    kq.append(i).append("^").append(somu);
                }
```
Có thể viết gọn hơn
```java
kq.append(i);
if (somu > 1){
  kq.append("^" + somu);
}
```

2019-05-14 15:03 UTC, voquanghoa commented on src/main/java/BT1/TongCSSN.java
> +    return tong;
Return viết lệch trái

2019-05-14 15:03 UTC, voquanghoa commented on src/main/java/BT1/UCLNandBCNN.java
> +        int tam1, tam2;
```java
int tam1, tam2;
tam1 = a;
tam2 = b;
```
Viết thành
```java
int tam1 = a;
int tam2 = b;
```

Nhưng mà không có lý do để tạo biến tam1, tam2 này lắm, dùng thẳng a, b cũng được mà

2019-05-14 15:03 UTC, voquanghoa commented on src/main/java/BT1/UCLNandBCNN.java
> +        while (tam1 != tam2) {
Lỡ a = 0 thì cái này lặp vô thời hạn

2019-05-14 15:03 UTC, voquanghoa commented on src/main/java/BT1/UCLNandBCNN.java
> +        return (a*b/tam1);
Có thể gọi hàm phía trên cho nhanh.

2019-05-14 15:03 UTC, voquanghoa commented on src/main/java/BT1/Fibonaci.java
> +package BT1;
Tên package phải viết thường`bt1`

2019-05-14 16:49 UTC, quangha12thxd commented on src/main/java/BT1/TichTSNT.java
> +        StringBuffer kq = new StringBuffer();
`kq` là chuỗi phải tạo trước khi chạy vòng lặp chứ anh?

2019-05-15 04:25 UTC, quangha12thxd commented on src/main/java/BT1/Fibonaci.java
> +        int tam;
done

2019-05-15 04:25 UTC, quangha12thxd commented on src/main/java/BT1/Fibonaci.java
> +    return str.toString();
done

2019-05-15 04:25 UTC, quangha12thxd commented on src/main/java/BT1/Fibonaci.java
> +public class Fibonaci {
done

2019-05-15 04:25 UTC, quangha12thxd commented on src/main/java/BT1/Fibonaci.java
> +    public String Fibonaci(int n) {
done

2019-05-15 04:25 UTC, quangha12thxd commented on src/main/java/BT1/PTB2.java
> +public class PTB2 {
done

2019-05-15 04:25 UTC, quangha12thxd commented on src/main/java/BT1/PTB2.java
> +                x1 = (double) Math.round(((-b + Math.sqrt(delta)) / 2 / a)*100)/100;
done

2019-05-15 04:25 UTC, quangha12thxd commented on src/main/java/BT1/PTB2.java
> +        double delta;
done

2019-05-15 04:27 UTC, quangha12thxd commented on src/main/java/BT1/PTB2.java
> +    // Kiem tra gia tri a
E tạo ghi chú đầu code để chi tiết về yêu cầu bài đó được không anh. (Mấy comment trong thân code thì đã xóa)

2019-05-15 04:27 UTC, quangha12thxd commented on src/main/java/BT1/PTB2.java
> +        double x1, x2;
done

2019-05-15 04:27 UTC, quangha12thxd commented on src/main/java/BT1/TichTSNT.java
> +            return kq.toString();
done

2019-05-15 04:27 UTC, quangha12thxd commented on src/main/java/BT1/TichTSNT.java
> +    return kq.toString();
done

2019-05-15 04:27 UTC, quangha12thxd commented on src/main/java/BT1/TichTSNT2.java
> +        int i, somu;
done

2019-05-15 04:28 UTC, quangha12thxd commented on src/main/java/BT1/TichTSNT2.java
> +            return kq.toString();
done

2019-05-15 04:28 UTC, quangha12thxd commented on src/main/java/BT1/TichTSNT2.java
> +                if (somu == 1) {
done

2019-05-15 04:28 UTC, quangha12thxd commented on src/main/java/BT1/TongCSSN.java
> +    return tong;
done

2019-05-15 04:28 UTC, quangha12thxd commented on src/main/java/BT1/UCLNandBCNN.java
> +        int tam1, tam2;
done

2019-05-15 04:28 UTC, quangha12thxd commented on src/main/java/BT1/UCLNandBCNN.java
> +        while (tam1 != tam2) {
done

2019-05-15 04:28 UTC, quangha12thxd commented on src/main/java/BT1/UCLNandBCNN.java
> +        return (a*b/tam1);
done

2019-05-15 04:28 UTC, quangha12thxd commented on src/main/java/BT1/Fibonaci.java
> +package BT1;
done

2019-05-15 13:50 UTC, voquanghoa approved these changes

2019-05-15 13:50 UTC, merged